name: Add issue to Team DIS project
on:
  pull_request:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/zalf-rdm/projects/2
          github-token: ${{ secrets.ACTION_TOKEN }}
 